apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/media
images:
  - name: threshold/media
    newName: core.harbor.domain/threshold/media
    digest: sha256:c8e338613167aedda294bb568a82b07e16dae5bedd749411945715b109eef2ba
patches:
  - target:
      kind: ConfigMap
      name: media-config
    patch: |-
      - op: replace
        path: /data/THRESHOLD_ENVIRONMENT
        value: local
