apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/media
images:
  - name: threshold/media
    newName: core.harbor.domain/threshold/media
    digest: sha256:a59b284266f5552171d8d00b97cebde713b6deae325c6763d1499397eb6a4b7b
patches:
  - target:
      kind: ConfigMap
      name: media-config
    patch: |-
      - op: replace
        path: /data/THRESHOLD_ENVIRONMENT
        value: local
