apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: users-postgres-backup-s3
  namespace: threshold
  labels:
    app.kubernetes.io/name: users-postgres
    app.kubernetes.io/component: database-backup
    app.kubernetes.io/part-of: threshold
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: users-postgres-backup-s3
    creationPolicy: Merge
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: threshold/cnpg/users-postgres/s3
        property: ACCESS_KEY_ID
    - secretKey: SECRET_ACCESS_KEY
      remoteRef:
        key: threshold/cnpg/users-postgres/s3
        property: SECRET_ACCESS_KEY
