apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - woodpecker-webhook-poller.yaml
  - woodpecker-github-oauth.yaml
  - woodpecker-github-writer.yaml
  - woodpecker-harbor-ci.yaml
