apiVersion: v1
kind: ConfigMap
metadata:
  name: woodpecker-release-config
  namespace: woodpecker
  labels:
    app.kubernetes.io/name: woodpecker-release-config
    app.kubernetes.io/part-of: threshold
data:
  REGISTRY: core.harbor.domain
  IMAGE_NAMESPACE: threshold
  IMAGE_REGISTRY: core.harbor.domain/threshold
  HARBOR_IP: 192.168.0.108
  HARBOR_CA_SHA256: 3f61f661906a658191c6cdf33b03d108bda9d2e635f7d894e34a403ee70cc4e9
  GITOPS_REPO_SLUG: fbialogrecki/threshold-gitops
  GITOPS_REPO_URL: https://github.com/fbialogrecki/threshold-gitops.git
