apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/auth-gateway
  - ingress.yaml
images:
  - name: threshold/auth-gateway
    newName: core.harbor.domain/threshold/auth-gateway
    digest: sha256:6100cfb8c1eeaf02f328e9cd5e61503f55887c2a8c4f8d48c0fc7fca77903d55
patches:
  - target:
      kind: ConfigMap
      name: auth-gateway-config
    patch: |-
      - op: replace
        path: /data/THRESHOLD_ENVIRONMENT
        value: local
