apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/auth-gateway
  - ingress.yaml
images:
  - name: threshold/auth-gateway
    newName: core.harbor.domain/threshold/auth-gateway
    digest: sha256:ed287492c3ee262bd887220094e7c5f46b8f3256c68e526b7db7e99b39d13ada
patches:
  - target:
      kind: ConfigMap
      name: auth-gateway-config
    patch: |-
      - op: replace
        path: /data/THRESHOLD_ENVIRONMENT
        value: local
