apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/auth-gateway
  - ingress.yaml
images:
  - name: threshold/auth-gateway
    newName: core.harbor.domain/threshold/auth-gateway
    digest: sha256:8f0efeb958dca6f7cc2dae6473cd768e742f55fb6efb9427d00e0095c7ddcebb
patches:
  - target:
      kind: ConfigMap
      name: auth-gateway-config
    patch: |-
      - op: replace
        path: /data/THRESHOLD_ENVIRONMENT
        value: local
