apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/users
images:
  - name: threshold/users
    newName: core.harbor.domain/threshold/users
    digest: sha256:afe5cec849f15e98cfa9ba6f899f09e0c4f1729d44402b9cd501f9c0fb1639e7
patches:
  - target:
      kind: ConfigMap
      name: users-config
    patch: |-
      - op: replace
        path: /data/THRESHOLD_ENVIRONMENT
        value: local
