apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/users
images:
  - name: threshold/users
    newName: core.harbor.domain/threshold/users
    digest: sha256:687c8a5fd77a433ab710d3956d7a324247810eb92bfc4a9a91cfbea78e9a881c
patches:
  - target:
      kind: ConfigMap
      name: users-config
    patch: |-
      - op: replace
        path: /data/THRESHOLD_ENVIRONMENT
        value: local
