apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/events
images:
  - name: threshold/events
    newName: core.harbor.domain/threshold/events
    digest: sha256:bef470e78a36ec0e0eece837d6a3f9cd280f305d209a8ee87648411d8b85c746
patches:
  - target:
      kind: ConfigMap
      name: events-config
    patch: |-
      - op: replace
        path: /data/THRESHOLD_ENVIRONMENT
        value: local
