apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/events
images:
  - name: threshold/events
    newName: core.harbor.domain/threshold/events
    digest: sha256:6722db84ec4745dcc3b90746a8dddff9c8a9bc4566861b152abe833465a52f3e
patches:
  - target:
      kind: ConfigMap
      name: events-config
    patch: |-
      - op: replace
        path: /data/THRESHOLD_ENVIRONMENT
        value: local
