apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/events
images:
  - name: threshold/events
    newName: core.harbor.domain/threshold/events
    digest: sha256:602e21b85b8ad103b3a3c4f09b73a47defc2aa4f8a55da4766cdfa417228fc7b
patches:
  - target:
      kind: ConfigMap
      name: events-config
    patch: |-
      - op: replace
        path: /data/THRESHOLD_ENVIRONMENT
        value: local
