apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: threshold-internal-tls
  namespace: threshold
spec:
  secretName: threshold-internal-tls
  commonName: threshold.internal
  dnsNames:
    - threshold.internal
  duration: 8760h
  renewBefore: 720h
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  usages:
    - server auth
  issuerRef:
    name: threshold-internal-ca
    kind: ClusterIssuer
