apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/web
  - ingress.yaml
patches:
  - path: auth-cookie-secure-patch.yaml
images:
  - name: threshold/web
    newName: core.harbor.domain/threshold/web
    digest: sha256:335fc36fcf14dc74b1af55ac267c550460217ce512892e0ce21f95aceb75eec8
