apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/web
  - ingress.yaml
patches:
  - path: auth-cookie-secure-patch.yaml
images:
  - name: threshold/web
    newName: core.harbor.domain/threshold/web
    digest: sha256:c945e2991632faeb3ee80494bc75cf4784b4e29dbcf2530965aa035204170ef0
