apiVersion: v1
kind: ConfigMap
metadata:
  name: social-config
  labels:
    app.kubernetes.io/name: social
    app.kubernetes.io/part-of: threshold
data:
  THRESHOLD_ENVIRONMENT: local
  THRESHOLD_SERVICE_NAME: social
  THRESHOLD_NATS_ENABLED: "true"
  THRESHOLD_NATS_URL: nats://nats.nats.svc.cluster.local:4222
  THRESHOLD_USERS_LIST_FOLLOWING_SUBJECT: users.follow.list_following.v1
  OTEL_SERVICE_NAME: social
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.observability.svc.cluster.local:4317
  OTEL_EXPORTER_OTLP_PROTOCOL: grpc
  OTEL_TRACES_EXPORTER: otlp
  OTEL_METRICS_EXPORTER: otlp
  OTEL_LOGS_EXPORTER: otlp
  OTEL_PYTHON_LOG_CORRELATION: "true"
  OTEL_RESOURCE_ATTRIBUTES: deployment.environment=local,service.namespace=threshold
