apiVersion: v1
kind: ServiceAccount
metadata:
  name: social
  labels:
    app.kubernetes.io/name: social
    app.kubernetes.io/part-of: threshold

imagePullSecrets:
  - name: harbor-threshold-puller
