apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: threshold-kube-state-metrics
  namespace: argocd
  labels:
    app.kubernetes.io/name: threshold-kube-state-metrics
    app.kubernetes.io/part-of: threshold
    app.kubernetes.io/component: observability
spec:
  project: platform
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-state-metrics
      targetRevision: 7.4.1
      helm:
        releaseName: kube-state-metrics
        valueFiles:
          - $values/infra/helm/kube-state-metrics/values.yaml
    - repoURL: git@github.com:fbialogrecki/threshold-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
