apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: threshold-otel-collector
  namespace: argocd
  labels:
    app.kubernetes.io/name: threshold-otel-collector
    app.kubernetes.io/part-of: threshold
    app.kubernetes.io/component: observability
spec:
  project: platform
  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-collector
      targetRevision: 0.157.0
      helm:
        releaseName: otel-collector
        valueFiles:
          - $values/infra/helm/otel-collector/values.yaml
    - repoURL: git@github.com:fbialogrecki/threshold-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
