apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: threshold-object-storage
  namespace: argocd
  labels:
    app.kubernetes.io/name: threshold-object-storage
    app.kubernetes.io/part-of: threshold
    app.kubernetes.io/component: object-storage
spec:
  project: platform
  source:
    repoURL: git@github.com:fbialogrecki/threshold.git
    targetRevision: gitops
    path: infra/kustomize/base/object-storage
  destination:
    server: https://kubernetes.default.svc
    namespace: seaweedfs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
