apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-oidc
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: server
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge
  data:
    - secretKey: oidc.authentik.clientSecret
      remoteRef:
        key: threshold/argocd/oidc
        property: clientSecret
