apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-internal-tls
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretName: argocd-internal-tls
  commonName: argocd.internal
  dnsNames:
    - argocd.internal
  duration: 8760h
  renewBefore: 720h
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  usages:
    - server auth
  issuerRef:
    name: threshold-internal-ca
    kind: ClusterIssuer
