apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: server
data:
  url: http://argocd.internal
  oidc.config: |
    name: Authentik
    issuer: http://authentik.internal/application/o/threshold-argocd/
    clientID: threshold-argocd
    clientSecret: $oidc.authentik.clientSecret
    requestedScopes: ["openid", "profile", "email"]
    requestedIDTokenClaims:
      groups:
        essential: true
