apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: server
data:
  policy.csv: |
    g, fbialogrecki@gmail.com, role:admin
    g, peregrin, role:admin
  policy.default: role:readonly
  policy.matchMode: glob
  scopes: '[groups, email, preferred_username]'
