apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - internal-ca.yaml
  - authentik-certificate.yaml
  - argocd-certificate.yaml
  - openbao-certificate.yaml
  - argocd-ingress.yaml
  - authentik-ingress.yaml
  - openbao-ingress.yaml
  - https-redirect-middlewares.yaml
  - argocd-cm-oidc.yaml
  - argocd-rbac-cm-sso.yaml
  - argocd-oidc-external-secret.yaml
