apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/social
images:
  - name: threshold/social
    newName: core.harbor.domain/threshold/social
    digest: sha256:1ea52c010c1fbf3b5c9d05571256d5624d321c624cb556bd3ce5afa0c0183ed9
patches:
  - target:
      kind: ConfigMap
      name: social-config
    patch: |-
      - op: replace
        path: /data/THRESHOLD_ENVIRONMENT
        value: local
