apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/social
images:
  - name: threshold/social
    newName: core.harbor.domain/threshold/social
    digest: sha256:b939b4b19bbd106a2999ad694d5fafca88961eeaea776819d6fca05d80aa8e86
patches:
  - target:
      kind: ConfigMap
      name: social-config
    patch: |-
      - op: replace
        path: /data/THRESHOLD_ENVIRONMENT
        value: local
